# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
            
    working_directory: /go/src/github.com/danesparza/iamserver
    steps:
      - checkout
      
      - run:
         name: Install 'dep' tool
         command: go get -u github.com/golang/dep/cmd/dep
      
      - run:
         name: Get dependencies
         command: dep ensure

      - run:
         name: API tests
         command: go test -v -race github.com/danesparza/iamserver/api

      - run:
         name: Auth tests
         command: go test -v -race github.com/danesparza/iamserver/auth

      - run:
         name: Data tests
         command: go test -v -race github.com/danesparza/iamserver/data
