# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
            
    working_directory: /go/src/github.com/danesparza/iamserver
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
         name: get dependencies
         command: dep ensure

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v -race ./... 